DROP TABLE IF EXISTS Users;
CREATE TABLE Users (
	Id INTEGER 
		CONSTRAINT PK_Users PRIMARY KEY AUTOINCREMENT,
	Name TEXT
		CONSTRAINT Not_Null NOT NULL,
	Password TEXT
		CONSTRAINT Not_Null NOT NULL,
	UserType INTEGER -- 0: players, 1: DM, 2:SuperAdmin
);

DROP TABLE IF EXISTS DiceRule;
CREATE TABLE DiceRule (
	Id INTEGER 
		CONSTRAINT PK_DiceRule PRIMARY KEY AUTOINCREMENT,
	Name TEXT
		CONSTRAINT Not_Null NOT NULL,
	OwnerId INTEGER 
		CONSTRAINT Not_Null NOT NULL 
		CONSTRAINT FK_Users REFERENCES Users (Id) ON DELETE CASCADE,
	RuleType INTEGER
);

DROP TABLE IF EXISTS RuleParam;
CREATE TABLE RuleParam (
	DiceRuleId INTEGER
		CONSTRAINT Not_Null NOT NULL 
		CONSTRAINT FK_DiceRule REFERENCES DiceRule (Id) ON DELETE CASCADE,
	ParamId INTEGER,
	ParamValue INTEGER,
	CONSTRAINT PK_RuleParam PRIMARY KEY (DiceRuleId, ParamId)
);